import { BookOpen, Brain, CheckCircle2, ChevronRight, Clock, Database, HelpCircle, Network, ShieldCheck, Users, X } from 'lucide-react'

const sections = [
  { icon: Brain, title: 'Ask AURORA', text: 'Ask questions and work with AURORA. Each response is persisted as a reasoning run, so you can inspect what happened rather than treating the answer as a black box.' },
  { icon: BookOpen, title: 'Knowledge', text: 'Add source material to the current workspace. AURORA can use these documents as evidence when answering questions.' },
  { icon: Network, title: 'Cognition', text: 'Inspect claims extracted from reasoning. Confidence, claim status and the evidence relationships are part of AURORA’s visible cognitive state.' },
  { icon: Clock, title: 'Runs & History', text: 'Review previous reasoning runs, including mode, provider/model, status, latency and when each run occurred.' },
]

export function UserGuide({ onClose }: { onClose: () => void }) {
  return <div className="fixed inset-0 z-[100] bg-black/75 backdrop-blur-sm flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-labelledby="aurora-guide-title">
    <div className="w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl border border-white/10 bg-[#0b0e14] shadow-2xl text-white">
      <div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/10 bg-[#0b0e14]/95 backdrop-blur px-6 py-5">
        <div><div className="flex items-center gap-3"><div className="rounded-lg bg-white/10 p-2"><Brain size={20}/></div><h1 id="aurora-guide-title" className="text-xl font-semibold">Welcome to AURORA</h1></div><p className="text-sm text-white/45 mt-1 ml-12">A practical guide to the transparent cognitive workspace</p></div>
        <button onClick={onClose} aria-label="Close user guide" title="Close user guide" className="rounded-lg p-2 text-white/50 hover:bg-white/10 hover:text-white"><X size={20}/></button>
      </div>
      <div className="p-6 md:p-8 space-y-8">
        <div className="rounded-xl border border-white/10 bg-white/[0.035] p-5"><div className="flex gap-3"><CheckCircle2 className="text-emerald-300 shrink-0" size={20}/><div><h2 className="font-medium">The quickest way to test AURORA</h2><ol className="mt-3 space-y-2 text-sm text-white/60 list-decimal pl-5"><li>Create or select a workspace.</li><li>Open <b className="text-white">Knowledge</b> and paste a short source document.</li><li>Return to <b className="text-white">Ask AURORA</b> and ask a question whose answer is contained in that document.</li><li>Inspect the answer and its provenance, claims, evidence and uncertainty.</li><li>Open <b className="text-white">Cognition</b> to see persisted claims, then <b className="text-white">Runs & History</b> to inspect the recorded reasoning run.</li></ol></div></div></div>
        <div><h2 className="text-lg font-medium mb-4">Navigation</h2><div className="grid md:grid-cols-2 gap-3">{sections.map(({icon:Icon,title,text})=><div key={title} className="rounded-xl border border-white/10 bg-white/[0.025] p-4"><div className="flex gap-3"><Icon size={19} className="text-white/70 shrink-0"/><div><h3 className="font-medium">{title}</h3><p className="text-sm text-white/45 mt-1 leading-6">{text}</p></div></div></div>)}</div></div>
        <div><h2 className="text-lg font-medium mb-4">Reasoning modes</h2><div className="grid md:grid-cols-2 gap-3 text-sm"><div className="rounded-xl border border-white/10 p-4"><b>Fast</b><p className="text-white/45 mt-1">Prioritises a quick response.</p></div><div className="rounded-xl border border-white/10 p-4"><b>Balanced</b><p className="text-white/45 mt-1">The normal AURORA starting point: useful reasoning without deliberately maximising cost or latency.</p></div><div className="rounded-xl border border-white/10 p-4"><b>Deep</b><p className="text-white/45 mt-1">Use when you want a more deliberate reasoning pass.</p></div><div className="rounded-xl border border-white/10 p-4"><div className="flex items-center gap-2"><Users size={16}/><b>QUORUM</b></div><p className="text-white/45 mt-1">Runs independent model contributions and then synthesises them. Disagreement is retained as a visible output rather than silently discarded.</p></div></div></div>
        <div><h2 className="text-lg font-medium mb-4">What makes AURORA different?</h2><div className="grid md:grid-cols-3 gap-3"><div className="rounded-xl border border-white/10 p-4"><ShieldCheck size={18} className="mb-3"/><b className="text-sm">Provenance</b><p className="text-xs text-white/40 mt-1">Provider, model and latency are recorded with reasoning runs.</p></div><div className="rounded-xl border border-white/10 p-4"><Database size={18} className="mb-3"/><b className="text-sm">Persistent state</b><p className="text-xs text-white/40 mt-1">Sessions, messages, documents, claims and evidence are stored in the workspace.</p></div><div className="rounded-xl border border-white/10 p-4"><Network size={18} className="mb-3"/><b className="text-sm">Inspectable cognition</b><p className="text-xs text-white/40 mt-1">Claims, evidence, uncertainty and model contributions can be examined instead of hidden behind one answer.</p></div></div></div>
        <div className="rounded-xl border border-amber-300/15 bg-amber-300/5 p-4 text-sm text-amber-100/75"><b className="text-amber-100">Important:</b> AURORA is an MVP. The transparency structures are real and persisted, but they should not be interpreted as proof that every model-generated claim is correct. Evidence quality and model output still need human scrutiny.</div>
        <div className="flex flex-col sm:flex-row gap-3 justify-between items-center border-t border-white/10 pt-5"><p className="text-xs text-white/35">You can reopen this guide at any time using the <HelpCircle className="inline" size={13}/> help button.</p><button onClick={onClose} className="inline-flex items-center gap-2 rounded-lg bg-white text-black px-5 py-2.5 text-sm font-medium">Start exploring <ChevronRight size={16}/></button></div>
      </div>
    </div>
  </div>
}
